version: '3'
services:
  vmu-api:
    container_name: vmu-api
    image: vmu-api
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: debug
      DATABASE_HOST: localhost
    ports:
      - '127.0.0.1:3003:3000'
    depends_on:
      - vmu-db
    # networks:
    #   - postgres
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  vmu-db:
    image: postgres:latest
    container_name: vmu-db
    build:
      context: ./sql
      dockerfile: Dockerfile
    env_file:
      - ../docker.env
    ports:
      - '127.0.0.1:5432:5432'
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
    # networks:
    #   - postgres

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    env_file:
      - ../docker.env
    ports:
      - '8080:80'
    # networks:
    #   - postgres
networks:
  postgres:
    driver: bridge
