version: '3.7'
services:
  vmu-api:
    container_name: vmu-api
    image: vmu-api
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: debug
      DATABASE_HOST: localhost
    ports:
      - '127.0.0.1:3003:3000'
    depends_on:
      - vmu-db
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  vmu-db:
    container_name: vmu-db
    build:
      context: ./mysql
    environment:
      MYSQL_HOST: '0.0.0.0'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: vmu
      MYSQL_USER: vmu
      MYSQL_PASSWORD: vmu
    ports:
      - '127.0.0.1:3307:3306'
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'
